name: app_example
description: "A new Flutter project."
publish_to: "none" #
version: 0.1.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  lib_dependencies:
    path: ../lib_dependencies
  lib_core:
    path: ../lib_core
  micro_calculator:
    path: ../micro_calculator
  micro_home:
    path: ../micro_home

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
